config/routes.rb
BlogOf7li::Application.routes.draw do

  resources :microposts

  devise_for :users

  resources :blogs do
    resources :comments, :only => [:create, :destroy]
  end

  resources :notices
  resources :readers, :only => [:create, :destroy]
  resources :messages, :only => [:index, :create, :destroy]

  match "/blogs/tag/:tag" => "blogs#tag", :as => "tagged_blogs", :via => :get

  root :to => "blogs#index"
  match "/about" => "home#about", :as => "about", :via => :get

  match "/archive" => "archive#index", :via => :get
  match "/archive/search" => "archive#search", :via => :post
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  attr_accessible :content, :title
  acts_as_taggable
  validates_presence_of :title, :content
  has_many :comments, :dependent => :destroy
  has_many :readers, :dependent => :destroy
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  # GET /blogs
  # GET /blogs.json

  load_and_authorize_resource #cancan use to authorize
  skip_authorize_resource :only => :tag

  def index
    @blogs = Blog.find(:all, :order => "created_at DESC")
    @micropost = Micropost.new

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @blogs }
    end
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @blog = Blog.find(params[:id])
    @comment = Comment.new
    @comment_floor

    #record the ip address of a reader
    #if two readers share a same ip then count it one
    reader_ip = request.remote_ip
    if Reader.find_by_ip_and_blog_id(reader_ip, @blog.id).nil?
      reader = Reader.new(:ip => reader_ip)
      @blog.readers << reader
      @blog.save
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @blog }
    end
  end

  # GET /blogs/new
  # GET /blogs/new.json
  def new
    @blog = Blog.new
    @tags = Blog.tag_counts

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @blog }
      format.js{ render :layout => false }
    end
  end

  # GET /blogs/1/edit
  def edit
    @blog = Blog.find(params[:id])
    @tags = @blog.tags
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(params[:blog])
    # add tags
    commit_tag

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render json: @blog, status: :created, location: @blog }
      else
        format.html { render action: "new" }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /blogs/1
  # PUT /blogs/1.json
  def update
    @blog = Blog.find(params[:id])
    #update tags
    commit_tag

    respond_to do |format|
      if @blog.update_attributes(params[:blog])
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url, notice: "Blog deleted"}
      format.json { head :no_content }
    end
  end

  #show blogs in tags
  def tag
    @blogs = Blog.tagged_with(params[:tag]).order("created_at DESC")
    @tag_name = params[:tag]
  end

private
  def commit_tag
    all_tags = Blog.tag_counts
    blog_tags = []

    all_tags.each do |tag|
      name = tag.name
      blog_tags << params[name]
    end

    params[:tag_to_add].split.each do |tag|
      blog_tags << tag
    end
    @blog.tag_list = blog_tags
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_comment.html.haml
- @comment_floor = comment_counter + 1 #use to store in model notice
%tr
  %td
    = comment.content.html_safe
  %td.blog-comment-slash
    .blog-comment-floor-wapper
      .blog-comment-user
        %i.icon-user
        %a{:name => "#{comment_counter}"}= comment.nick_name
      .blog-comment-floor
        %b= "F" + (comment_counter+1).to_s
  - if can? :manage, :all
    %td= link_to "Delete", blog_comment_path(@blog, comment),
      :method => :delete,:confirm => "Delete?"

app/views/blogs/_comment_form.html.haml
= form_for @comment, :url => blog_comments_path(@blog)  do |f|
  %div.content
    = f.kindeditor :content, :items => [ 'undo', 'redo','|',
      'code','image',
      'emoticons','table', 'link', '|', 'source', 'preview','|',
      'justifyleft', 'justifycenter', 'justifyright', 'justifyfull', 'insertorderedlist',
      'insertunorderedlist', 'subscript', 'superscript', '|',
      'formatblock', 'fontname', 'fontsize', '|',
      'forecolor', 'hilitecolor', 'bold', 'italic', 'underline', 'strikethrough',
      'lineheight', '|', 'removeformat', 'plainpaste', 'quickformat', 'fullscreen'],
      :wellFormatMode => true, :allowImageUpload => false,
      :height => 100
  %div.new-comment-nickname
    = f.text_field :nick_name,
      :class => "new-comment-nickname-form",
      :placeholder => " Mr. Who? It's optional"
    %i.icon-user
  = hidden_field_tag "comment_floor", @comment_floor
  %div
    = f.submit "Comment", :class => "btn btn-info"

app/views/blogs/_form.html.haml
= form_for @blog do |f|
  -if @blog.errors.any?
    #error_explanation
      %h2= "#{pluralize(@blog.errors.count, "error")} prohibited this blog from being saved:"
      %ul
        - @blog.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.text_field :title
    %i.icon-pencil
    Title
  .field
    = f.kindeditor :content, :width => 800, :height => 300 #use kindeditor
  #tag
    = render :partial => 'tag', :collection =>  @tags
  %br
  = text_field_tag "tag_to_add"
  %i.icon-tag
  new tag
  .actions
    = f.submit 'Save', :class => "btn btn-info"

app/views/blogs/_tag.html.haml
- if @blog.new_record?
  = check_box_tag "#{tag.name}", "#{tag.name}"
- else
  = check_box_tag "#{tag.name}", "#{tag.name}", true
= tag.name

app/views/blogs/_tagged_blog.html.haml
%tr
  %td.blog_title
    = link_to tagged_blog.title, blog_url(tagged_blog)
  %td
    = tagged_blog.created_at.mon
    \/
    = tagged_blog.created_at.day
    \/
    = tagged_blog.created_at.year
    %br
    - if can? :manage, :all
      %td= link_to 'Edit', edit_blog_path(tagged_blog),
        :class => "btn btn-mini"
      %td= link_to 'Destroy', tagged_blog, 
        :method => :delete, :confirm => "Remove?",
        :class => "btn btn-mini btn-danger"

app/views/blogs/edit.html.haml
= render 'form'

= link_to 'Show', @blog, :class => "btn btn-mini"
= link_to 'Back', blogs_path, :class => "btn btn-mini"

app/views/blogs/index.html.haml
- if can? :manage, Micropost
  - content_for :micropost do
    = render "microposts/form"
.blog-recentpost-head
  %span.recent-post-tag Recent Posts
= render "share/blog_table", :blog_table => @blogs

app/views/blogs/new.html.haml
= render 'form'

app/views/blogs/show.html.haml
- if can? :manage, :all
  = link_to 'Edit', edit_blog_path(@blog),
    :class => "btn btn-mini"
  = link_to 'Destroy', blog_path(@blog), :method => :delete,
    :class => "btn btn-mini", :confirm => "Delete this blog ?"
%h3
  = @blog.title
  %span.label
    = @blog.readers.size
    %i.icon-eye-open
    = @blog.comments.size
    %i.icon-comment

.blog-content
  = @blog.content.html_safe
.comments
  %table.table.table-striped
    %thead
      %tr
        %h3
          Total comments
          %span.total-comments= @blog.comments.size
    %tbody
      = render :partial => "comment", :collection => @blog.comments
%h3 Comment:
.new-comment
  = render "comment_form"
= link_to 'Back', blogs_path, :class => "btn btn-mini"

app/views/blogs/tag.html.haml
.blog-tag-head
  %span.recent-post-tag
    = @tag_name.humanize
=  render 'share/blog_table', :blog_table => @blogs