config/routes.rb
BlogOf7li::Application.routes.draw do

  resources :microposts

  devise_for :users

  resources :blogs do
    resources :comments, :only => [:create, :destroy]
  end

  resources :notices
  resources :readers, :only => [:create, :destroy]
  resources :messages, :only => [:index, :create, :destroy]

  match "/blogs/tag/:tag" => "blogs#tag", :as => "tagged_blogs", :via => :get

  root :to => "blogs#index"
  match "/about" => "home#about", :as => "about", :via => :get

  match "/archive" => "archive#index", :via => :get
  match "/archive/search" => "archive#search", :via => :post
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  attr_accessible :content
  validates_presence_of :content, :message => "shouldn't be blank, right?"
  belongs_to :user
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  # GET /microposts
  # GET /microposts.json
  load_and_authorize_resource #cancan use to authorize
  def index
    @microposts = Micropost.find(:all, :order => "created_at DESC")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @microposts }
    end
  end

  # GET /microposts/1
  # GET /microposts/1.json
  def show
    @micropost = Micropost.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @micropost }
    end
  end

  # GET /microposts/new
  # GET /microposts/new.json
  def new
    @micropost = Micropost.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @micropost }
    end
  end

  # GET /microposts/1/edit
  def edit
    @micropost = Micropost.find(params[:id])
  end

  # POST /microposts
  # POST /microposts.json
  def create
    @micropost = Micropost.new(params[:micropost])
    current_user.microposts << @micropost


    respond_to do |format|
      if current_user.save
        format.html { redirect_to root_url, notice: 'Micropost sended' }
        format.json { render json: @micropost, status: :created, location: @micropost }
      else
        format.html { redirect_to root_url, alert: @micropost.errors.full_messages.first }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /microposts/1
  # PUT /microposts/1.json
  def update
    @micropost = Micropost.find(params[:id])

    respond_to do |format|
      if @micropost.update_attributes(params[:micropost])
        format.html { redirect_to @micropost, notice: 'Micropost was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microposts/1
  # DELETE /microposts/1.json
  def destroy
    @micropost = Micropost.find(params[:id])
    @micropost.destroy

    respond_to do |format|
      format.html { redirect_to microposts_url, notice: "Minipost deleted" }
      format.json { head :no_content }
    end
  end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_form.html.haml
= form_for @micropost do |f|
  -if @micropost.errors.any?
    #error_explanation
      %h2= "#{pluralize(@micropost.errors.count, "error")} prohibited this micropost from being saved:"
      %ul
        - @micropost.errors.full_messages.each do |msg|
          %li= msg
          %h3
            Total comments
            = @blog.comments.size

  .field
    = f.text_area :content, :class => "micropost-content"
    = f.submit 'Save', :class => "btn btn-mini btn-info"

app/views/microposts/_micropost.html.haml
.micropost
  %span.micropost-serial-number
    \#
    = micropost_counter + 1
  = micropost.content
  %hr.micropost-hr
  = micropost.created_at
  - if can? :manage, Micropost
    = link_to "Delete", micropost,
      :method => :delete, :confirm => "Delete this minipost?"

app/views/microposts/edit.html.haml
%h1 Editing micropost

= render 'form'

= link_to 'Show', @micropost
\|
= link_to 'Back', microposts_path

app/views/microposts/index.html.haml
= render :partial => "micropost", :collection => @microposts

app/views/microposts/new.html.haml
%h1 New micropost

= render 'form'

= link_to 'Back', microposts_path

app/views/microposts/show.html.haml
%p
  %b Content:
  = @micropost.content

- if can? :manage, Micropost
  = link_to 'Edit', edit_micropost_path(@micropost)
  \|
  = link_to 'Back', microposts_path