config/routes.rb
BlogOf7li::Application.routes.draw do

  resources :microposts

  devise_for :users

  resources :blogs do
    resources :comments, :only => [:create, :destroy]
  end

  resources :notices
  resources :readers, :only => [:create, :destroy]
  resources :messages, :only => [:index, :create, :destroy]

  match "/blogs/tag/:tag" => "blogs#tag", :as => "tagged_blogs", :via => :get

  root :to => "blogs#index"
  match "/about" => "home#about", :as => "about", :via => :get

  match "/archive" => "archive#index", :via => :get
  match "/archive/search" => "archive#search", :via => :post
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new(:admin => false) # guest user 
    if user.admin?
      can :manage, :all
    else
      can :read, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  attr_accessible :content, :title
  acts_as_taggable
  validates_presence_of :title, :content
  has_many :comments, :dependent => :destroy
  has_many :readers, :dependent => :destroy
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :content, :nick_name
  validates_presence_of :content,
                        :message => "shouln't be blank, right?"
  belongs_to :blog
  has_many :notices, :dependent => :destroy
  has_many :users, :through => :notices
end

app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessible :content
  validates_presence_of :content, :message => "shouln't be blank, right?"
  belongs_to :user
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  attr_accessible :content
  validates_presence_of :content, :message => "shouldn't be blank, right?"
  belongs_to :user
end

app/models/notice.rb
class Notice < ActiveRecord::Base
  attr_accessible :comment_blog_id, :comment_floor
  belongs_to :user
  belongs_to :comment
end

app/models/reader.rb
class Reader < ActiveRecord::Base
  attr_accessible :blog_id, :ip
  belongs_to :blog
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :admin
  # attr_accessible :title, :body

  has_many :notices, :dependent => :destroy
  has_many :comments, :through => :notices
  has_many :microposts, :dependent => :destroy
  has_many :messages, :dependent => :destroy

  def admin?
    admin == true
  end
end

app/controllers/archive_controller.rb
class ArchiveController < ApplicationController
  def index
    @blogs = Blog.all
    @tags = Blog.tag_counts

    first_blog_year = Blog.first.created_at.year
    last_blog_year = Blog.last.created_at.year
    @years = first_blog_year..last_blog_year

    @months = 1..12

  end

  def search
    @blogs = Blog.find(:all, "created_at DESC")
    if params[:year]
      if params[:year] != "all"
        @blogs.select!{|blog| blog.created_at.year.to_s == params[:year]}
      end
    end

    if params[:month]
      if params[:month] != "all"
        @blogs.select!{|blog| blog.created_at.month.to_s == params[:month]}
      end
    end

    if params[:tag]
      if params[:tag] != "all"
        @blogs.select!{|blog| blog.tag_list.include?(params[:tag])}
      end
    end

    respond_to do |format|
      format.html
      format.js
    end
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  # GET /blogs
  # GET /blogs.json

  load_and_authorize_resource #cancan use to authorize
  skip_authorize_resource :only => :tag

  def index
    @blogs = Blog.find(:all, :order => "created_at DESC")
    @micropost = Micropost.new

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @blogs }
    end
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @blog = Blog.find(params[:id])
    @comment = Comment.new
    @comment_floor

    #record the ip address of a reader
    #if two readers share a same ip then count it one
    reader_ip = request.remote_ip
    if Reader.find_by_ip_and_blog_id(reader_ip, @blog.id).nil?
      reader = Reader.new(:ip => reader_ip)
      @blog.readers << reader
      @blog.save
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @blog }
    end
  end

  # GET /blogs/new
  # GET /blogs/new.json
  def new
    @blog = Blog.new
    @tags = Blog.tag_counts

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @blog }
      format.js{ render :layout => false }
    end
  end

  # GET /blogs/1/edit
  def edit
    @blog = Blog.find(params[:id])
    @tags = @blog.tags
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(params[:blog])
    # add tags
    commit_tag

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render json: @blog, status: :created, location: @blog }
      else
        format.html { render action: "new" }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /blogs/1
  # PUT /blogs/1.json
  def update
    @blog = Blog.find(params[:id])
    #update tags
    commit_tag

    respond_to do |format|
      if @blog.update_attributes(params[:blog])
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url, notice: "Blog deleted"}
      format.json { head :no_content }
    end
  end

  #show blogs in tags
  def tag
    @blogs = Blog.tagged_with(params[:tag]).order("created_at DESC")
    @tag_name = params[:tag]
  end

private
  def commit_tag
    all_tags = Blog.tag_counts
    blog_tags = []

    all_tags.each do |tag|
      name = tag.name
      blog_tags << params[name]
    end

    params[:tag_to_add].split.each do |tag|
      blog_tags << tag
    end
    @blog.tag_list = blog_tags
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/archive_helper.rb
module ArchiveHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/helpers/readers_helper.rb
module ReadersHelper
end

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
    %a.close{"data-dismiss" => "alert"} ×
    = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/layouts/_navigation.html.haml
%ul.nav.nav-pills
  %li
    = link_to "7LI",root_path , :class => 'brand'
  %li
    %a{:href => "/microposts"}
      %i.icon-comment
      Minipost
  %li
    %a{:href => "/archive"}
      %i.icon-list-alt
      Archive
  %li
    %a{:href => "/messages"}
      %i.icon-envelope
      %span.application-message-numbers
        = Message.all.size

  - if can? :manage, :all
    %li
      %a{:href => "/blogs/new"}
        %i.icon-pencil
    %li
      %a{:href => "/notices"}
        = Notice.all.size

  %li.dropdown
    %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
      %i.icon-user
      %b.caret
    %ul.dropdown-menu
      = link_to_unless_current "Log in", new_user_session_url
      = link_to "Log out", destroy_user_session_url, :method => :delete
      = link_to "About", about_url

app/views/layouts/_tags.html.haml
- Blog.tag_counts.each do |tag|
  %tr
    %td
      = link_to_unless_current tag.name+" ("+Blog.tagged_with(tag.name).size.to_s + ")",
        tagged_blogs_url(tag.name)

app/views/layouts/_top_jquery_plugin.html.haml
= stylesheet_link_tag "/top_jquery_plugin/css/manhuatoTop.1.0"
= javascript_include_tag "/top_jquery_plugin/js/manhuatoTop.1.0"
:javascript
  $(function (){
  $(window).manhuatoTop({
  showHeight : 100,//设置滚动高度时显示
  speed : 370 //返回顶部的速度以毫秒为单位
  });
  });

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %title= content_for?(:title) ? yield(:title) : "7LI"
    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "author"}
    = favicon_link_tag 'favicon.png', :type => 'image/png'
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = yield(:head)

    -#the back to top jquery plugin
    = render "layouts/top_jquery_plugin"

  %body
    %header.navbar.navbar-fixed-top
      %nav.navbar-mycustume
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container-fluid
        .content
          .row-fluid
            = yield(:micropost)
          .row-fluid
            = render 'layouts/messages'
            = yield
    %footer
      = debug(params) if Rails.env.development?

app/views/layouts/blogs.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %title= content_for?(:title) ? yield(:title) : "7LI"
    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "author"}
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = yield(:head)

    -#the back to top jquery plugin
    = render "layouts/top_jquery_plugin"

  %body
    %header.navbar.navbar-fixed-top
      %nav.navbar-mycustume
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container-fluid
        .content
          .row-fluid
            = yield(:micropost)
          .row-fluid
            .well.application-tag
              = render '/layouts/tags'
          .row-fluid
            = render 'layouts/messages'
            = yield
    %footer
      = debug(params) if Rails.env.development?

app/views/layouts/home.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %title= content_for?(:title) ? yield(:title) : "7LI"
    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "author"}
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags

%body#welcome
= yield

app/views/layouts/microposts.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %title= content_for?(:title) ? yield(:title) : "7LI"
    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "author"}
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = yield(:head)

    -#the back to top jquery plugin
    = render "layouts/top_jquery_plugin"

  %body
    %header.navbar.navbar-fixed-top
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container-fluid
        .content
          .row-fluid
            = yield(:micropost)
          .row-fluid
            = render 'layouts/messages'
            = yield
    %footer
      = debug(params) if Rails.env.development?

app/views/share/_blog_table.html.haml
%table.blog-table
  - blog_table.each do |blog|
    %tr
      %td.blog_title
        = link_to blog.title, blog_url(blog)
      %td
        %span
          = blog.readers.size
          %i.icon-eye-open
      %td
        %span
          = blog.comments.size
          %i.icon-comment
      %td
        = blog.created_at.mon
        \/
        = blog.created_at.day
        \/
        = blog.created_at.year
        - if can? :manage, :all
          %td= link_to 'Edit', edit_blog_path(blog)
          %td= link_to 'Destroy', blog, :method => :delete,
            :confirm => "Remove?"